import { Inter } from 'next/font/google';
import '../globals.css';
import '@/styles/custom.css';

import Header from '@/components/layout/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body className={inter.className}>
        <main>
          <Header headerPrimary={true} />

          {children}
        </main>
      </body>
    </html>
  );
}
